```{r}
library(tidyverse)
library(plotly)
df <- read_csv('grouped_plot.csv')

```

```{r}
library(tidyverse)
library(plotly)
df <- read_csv('grouped_plot_ru.csv')


y <- df$var
x1 <- df[['Not online']]
x2 <- df[["Uses internet, not on Facebook"]]
x3 <- df[["Facebook user"]]

data <- data.frame(y, x1, x2, x3)

data$y <- factor(data$y, levels = data$y)

fig <- plot_ly(data, x = ~x1, y = ~y, type = 'bar', orientation = 'h', name='Без интернета', legendgroup = '3',
        marker = list(color = 'rgba(38, 24, 74, 0.8)',
                      line = list(color = 'rgb(248, 248, 249)', width = 1))) 
fig <- fig %>% add_trace(x = ~x2, marker = list(color = 'rgba(71, 58, 131, 0.8)'), name='Пользуется интернетом, но не Facebook', legendgroup = '2') 
fig <- fig %>% add_trace(x = ~x3, marker = list(color = 'rgba(122, 120, 168, 0.8)'), name='Пользуется Facebook', legendgroup = '1') 

fig <- fig %>% layout(xaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE,
                      domain = c(0.15, 1)),
         yaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE),
         barmode = 'stack',
         paper_bgcolor = 'rgb(248, 248, 255)', plot_bgcolor = 'rgb(248, 248, 255)',
         margin = list(l = 120, r = 10, t = 140, b = 80),
         showlegend = TRUE)


fig <- fig %>% add_annotations(xref = 'paper', yref = 'y', x = 0.14, y = y,
                  xanchor = 'right',
                  text = y,
                  font = list(family = 'Arial', size = 12,
                            color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE, align = 'right') 
  # labeling the percentages of each bar (x_axis)
fig <- fig %>% add_annotations(xref = 'x', yref = 'y',
                  x = x1 / 2, y = y,
                  text = paste(round(data[,"x1"] * 100, 0), '', sep=''),
                  font = list(family = 'Arial', size = 9,
                            color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) 
fig <- fig %>% add_annotations(xref = 'x', yref = 'y',
                  x = x1 + x2 / 2, y = y,
                  text = paste(round(data[,"x2"] * 100, 0), '', sep=''),
                  font = list(family = 'Arial', size = 9,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) 
fig <- fig %>% add_annotations(xref = 'x', yref = 'y',
                  x = x1 + x2 + x3 / 2, y = y,
                  text = paste(round(data[,"x3"] * 100, 0), '', sep=''),
                  font = list(family = 'Arial', size = 9,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) 


cuts <- seq(0,1, length.out=length(y)+1)
cut_lines <- list()
notes <- list()
for (k in 1:length(y)+1){
  if (k %in% c(1,4,7,9,15,18)){
    cut_line <- list(
        line = list(
          color = "rgba(68, 68, 68, 0.5)",
          width = 1
        ),
        type = "line",
        x0 = -0.3,
        x1 = 1,
        xref = "paper",
        y0 = cuts[k],
        y1 = cuts[k],
        yref = "paper"
      )
    cut_lines[[length(cut_lines)+1]] <- cut_line
  }
}

note_cuts <- cuts <- seq(0,1, length.out=length(y))
labs <- c("<b>Показатель<br>благосостояния</b>", "<b>Возраст</b>", "<b>Пол</b>", "<b>Образование</b>", "<b>Населённый<br>пункт</b>")
adj <- c(-0.012, -0.001, 0.006, -0.007, -0.016)
n = 1
for (k in 1:length(y)){
  if (k %in% c(3,6,8,14,17)){
          note = list(
            x = -0.3,
            y = note_cuts[k] + adj[n],
            showarrow = FALSE,
            text = labs[n],
            align = 'left',
            xref = "paper",
            yref = "paper"
        )
    notes[[length(notes)+1]] <- note
    n = n + 1
    }
}

fig <- fig %>% layout(
    title = 'Вероятность того, что респонденты не пользуются интернетом,<br>пользуются Facebook и того, что они пользуются интернетом, но не Facebook<br>(Опрос NDI/CRRC, ноябрь-декабрь 2019 г.)',
    yaxis = list(
      autorange = TRUE,
      # categoryorder = "category descending",
      domain = c(0, 1),
      range = c(-0.5, 3),
      showline = TRUE,
      title = "",
      type = "category"
    ),
    margin = list(
      r = 10,
      t = 120,
      b = 40,
      l = 110
    ),
    legend = list(orientation='h',
      x = -0.3,
      y = 0
    ),
    shapes = cut_lines,
    annotations = notes
    )
fig
htmlwidgets::saveWidget(as_widget(fig), "chart1_ru.html")
```

```{r}
df <- readxl::read_xlsx('bar_plot_2_ru.xlsx')
fig <- plot_ly(df, x = ~g, y = ~fb, type = 'bar', name='???????????????????? Facebook', legendgroup = '3',
               marker = list(color = 'rgba(38, 24, 74, 0.8)',
                      line = list(color = 'rgb(248, 248, 249)', width = 1))) 
fig <- fig %>% add_trace(y = ~nfb, name = '????????????, ???? ???? ???? Facebook', marker = list(color = 'rgba(122, 120, 168, 0.8)')) %>%
               layout(title='???????????????????????????? ?????????????? ?????????? ??????????????,<br>?????????? ?????????????????????? ???????????????????????? ???????????????? ?? ????????????????, ?????? ???? ??????????,<br>?? ?????????????????????? ???? ????????, ???????????????????? ???? ?????? Facebook', yaxis = list(title = "", range = c(0,50)), xaxis = list(title=''), margin = list(t=115))


htmlwidgets::saveWidget(as_widget(fig), "pred_times_ru.html")
```
